name: Build OpenWrt MiniEAP with ImmortalWrt SDK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout MiniEAP
      uses: actions/checkout@v2
      with:
        repository: kongfl888/openwrt-minieap
        path: package/minieap

    - name: Download ImmortalWrt SDK
      run: |
        wget https://downloads.immortalwrt.org/releases/18.06.9/targets/x86/64/immortalwrt-sdk-18.06.9-x86-64_gcc-8.4.0_musl.Linux-x86_64.tar.xz
        tar xJf immortalwrt-sdk-*.tar.xz
        mv immortalwrt-sdk-* sdk

    - name: Update feeds
      working-directory: sdk
      run: |
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Configure SDK
      working-directory: sdk
      run: |
        echo 'CONFIG_PACKAGE_minieap=y' >> .config
        make defconfig

    - name: Build MiniEAP
      working-directory: sdk
      run: |
        make package/minieap/compile V=s -j$(nproc)

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: minieap-package
        path: sdk/bin/packages/*/base/minieap_*.ipk
