name: Build OpenWrt MiniEAP for ImmortalWrt 18.06

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout ImmortalWrt SDK
      uses: actions/checkout@v2
      with:
        repository: immortalwrt/immortalwrt
        ref: openwrt-18.06
        fetch-depth: 0

    - name: Update and install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential ccache ecj fastjar file g++ gawk \
        gettext git java-propose-classpath libelf-dev libncurses5-dev \
        libncursesw5-dev libssl-dev python python2.7-dev python3 unzip wget \
        python3-distutils python3-setuptools rsync subversion swig time \
        xsltproc zlib1g-dev

    - name: Update feeds
      run: |
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Clone MiniEAP
      run: |
        git clone https://github.com/kongfl888/openwrt-minieap.git package/minieap

    - name: Configure ImmortalWrt
      run: |
        echo 'CONFIG_PACKAGE_minieap=y' >> .config
        echo 'CONFIG_TOOLCHAINOPTS=y' >> .config
        echo 'CONFIG_MUSL_DISABLE_CRYPT_SIZE_HACK=y' >> .config
        make defconfig

    - name: Download package
      run: |
        make download -j8
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;

    - name: Build toolchain
      run: |
        make toolchain/install -j$(nproc)

    - name: Build MiniEAP
      run: |
        make package/minieap/compile V=s -j$(nproc)

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: minieap-package
        path: bin/packages/*/base/minieap_*.ipk
