# [K] (c)@2020

name: Test

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/main.yml'
jobs:

  build:

    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:

      - name: Checkout
        uses: actions/checkout@main
        with:
          ref: main

      - name: Initialization Environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo rm -rf /etc/apt/sources.list.d
          sudo apt-get update
          sudo apt-get -y install bc build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler
          wget -O - https://raw.githubusercontent.com/friendlyarm/build-env-on-ubuntu-bionic/master/install.sh | bash
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android/sdk
          git config --global user.name "kongfl888"
          git config --global user.email "kongfl888@outlook.com"
      - name: Init Source
        run: |
          wget --no-check-certificate -O openwrt-sdk.tar.xz https://downloads.openwrt.org/snapshots/targets/rockchip/armv8/openwrt-sdk-rockchip-armv8_gcc-8.4.0_musl.Linux-x86_64.tar.xz
          xz -d openwrt-sdk.tar.xz && tar -xvf openwrt-sdk.tar
          mv -f openwrt-sdk-* openwrt-sdk
          git clone https://github.com/kongfl888/openwrt-minieap.git ./openwrt-sdk/package/minieap
          sed -i '/MAINTAINER:=updateing/i\\tPKGARCH:=aarch64_cortex-a53' openwrt-sdk/package/minieap/Makefile
          make -C openwrt-sdk defconfig
          sed -i '/CONFIG_TARGET_ARCH_PACKAGES/d' openwrt-sdk/.config
          echo '
          CONFIG_TARGET_DEVICE_PACKAGES_rockchip_armv8_DEVICE_friendlyarm_nanopi-r2s=y
          CONFIG_TARGET_ARCH_PACKAGES="aarch64_cortex-a53"
          CONFIG_PACKAGE_minidlna=y
          ' >> openwrt-sdk/.config
      - name: Build
        run: |
          #./openwrt-sdk/scripts/feeds update -a && ./openwrt-sdk/scripts/feeds install -a
          cd openwrt-sdk
          make package/minieap/compile V=s
          ls openwrt-sdk/bin/packages || echo ""
      - name: Archive build output
        uses: actions/upload-artifact@v1
        with:
          name: output
          path: openwrt-sdk/bin/packages
